train:
  - _target_: src.datasets.LibrispeechDataset
    part: "train-clean-100"
    data_dir: "/kaggle/input/librispeech-clean/LibriSpeech"
    is_kaggle: True
    max_audio_length: 20.0
    max_text_length: 250
    log_spec: True
    instance_transforms: ${transforms.instance_transforms.train_noise}
  - _target_: src.datasets.LibrispeechDataset
    part: "train-clean-360"
    data_dir: "/kaggle/input/librispeech-clean/LibriSpeech"
    is_kaggle: True
    max_audio_length: 20.0
    max_text_length: 250
    log_spec: True
    instance_transforms: ${transforms.instance_transforms.train_noise}
  - _target_: src.datasets.LibrispeechDataset
    part: "train-other-500"
    data_dir: "/kaggle/input/librispeech-clean/LibriSpeech"
    is_kaggle: True
    max_audio_length: 20.0
    max_text_length: 250
    log_spec: True
    instance_transforms: ${transforms.instance_transforms.train}
val:
  - _target_: src.datasets.LibrispeechDataset
    part: "dev-other"
    data_dir: "/kaggle/input/librispeech-clean/LibriSpeech"
    is_kaggle: True
    log_spec: True
    instance_transforms: ${transforms.instance_transforms.inference}
