train:
  data_object: # name of the tensor on which we apply transform
    _target_: torch.nn.Sequential # to apply several transforms sequentially
    _args_:
      - _target_: src.transforms.spec_augs.TimeStretch
        rate_std: 0.1
      - _target_: src.transforms.spec_augs.FrequencyMasking
        freq_mask_param: 27
      - _target_: src.transforms.spec_augs.TimeMasking
        time_mask_param: 100
inference:
  null
