defaults:
  - model: conformer
  - metrics: wer_cer
  - datasets: librispeech_test # we do not want to run inference on training data
  - dataloader: base
  - transforms: spec_aug_gain
  - _self_
inferencer:
  device_tensors: ["data_object", "labels"] # which tensors should be on device (ex. GPU)
  device: auto # device name or "auto"
  save_path: "example" # any name here, can be a dataset name
  seed: 42
  from_pretrained: "saved/model_best.pth" # path to the pretrained model
